services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: time_deposit
      POSTGRES_USER: time_deposit
      POSTGRES_PASSWORD: time_deposit
    ports:
      - "5432:5432"
